perPage: 10

header:
    -   name: Home
        path: /
    - 
        name: Notes
        path: notes
    - 
        name: About
        path: about

profile:
    nickname: ä¸€å°Šè¿˜é…¹æ±ŸæœˆğŸˆä¸¶
    exp: åŠæ ˆå·¥ç¨‹å¸ˆ | è¿˜è¦åŠ æ²¹å“¦~
    social:
        github: https://github.com/feiiyuu
    info:
        å…´è¶£çˆ±å¥½: ğŸµ/ğŸƒ/ğŸ®/ğŸŠâ€â™‚ï¸
        å‡ºèº«å¹´æœˆ: 2000/07/15


home:
    text: Hi,there.ğŸ‘‹Welcome to my homepage!