perPage: 4

header:
    -   name: Home
        path: /
    - 
        name: Notes
        path: notes
    - 
        name: About
        path: about

profile:
    nickname: ä¸€å°Šè¿˜é…¹æ±ŸæœˆğŸˆä¸¶
    exp: åŠæ ˆå·¥ç¨‹å¸ˆ | è¿˜è¦åŠ æ²¹å“¦~
    social:
        github: https://github.com/feiiyuu
        email: mailto:wangb.edu@gmail.com
        bilibili: https://space.bilibili.com/99907586
    info:
        Identity: ğŸ‘¨â€ğŸ“->ğŸ®ğŸ´......ğŸ˜…
        Hobby: ğŸµ/ğŸƒ/ğŸ®/ğŸŠâ€â™‚ï¸/ğŸš
        Birthday: 2000/07/15


home:
    text: Hi,there.ğŸ‘‹ Welcome to my homepage!